### ISSUE TITLE
How to run SenCID on normalized data, such TPM data?

### ISSUE THREAD

**Issue by KOBE24DUNK** [JackieHanLab/SenCID#9]
Hi,

Thanks for the great and strong tool. But I found it only accepts count data. Is it possible to run SenCID on normalized data?

Thank you!

**Comment by SherryMiyano** [comment]
Hello, Well,,, I know sometimes there might be challenging to regain the count matrix from the processed data,,
The necessity to use count data is due to the dependency [DCA](https://github.com/theislab/dca), which needs the count matrix to impute single cell data. 
If you are not using single cell data, just turn off the DCA by parameter 'denoizing = False' would allow non-integer matrix input. Another way is to round the normalized data to positive integers. However, it should be noted that normalized data would change the distribution of transcriptomes, which may cause inaccuracy of the results.

**Comment by KOBE24DUNK** [comment]
Cool, got it. Thanks a lot!

**Comment by KOBE24DUNK** [comment]
> [SherryMiyano](/SherryMiyano)

Cool, got it. Thanks a lot!
